# Generated by Django 2.1.1 on 2019-01-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storytags',
            options={'verbose_name_plural': 'Story tags'},
        ),
    ]
