# Generated by Django 2.1.1 on 2019-01-19 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_headline', models.CharField(blank=True, max_length=70)),
                ('story_publish_date', models.DateTimeField(auto_now_add=True)),
                ('story_first_paragraph', models.TextField(blank=True, max_length=1000)),
                ('slug', models.SlugField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Original stories',
            },
        ),
        migrations.CreateModel(
            name='UserStoryParagraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_paragraph', models.TextField(max_length=1000)),
                ('user_paragraph_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date added')),
            ],
            options={
                'verbose_name_plural': 'User paragraphs',
            },
        ),
    ]
