# Generated by Django 2.1.4 on 2019-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalstory',
            name='story_first_paragraph',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
