# Generated by Django 2.1.1 on 2019-01-19 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstoryparagraphs',
            name='paragraph_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='para_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstoryparagraphs',
            name='story_belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='mainsite.OriginalStory'),
        ),
        migrations.AddField(
            model_name='originalstory',
            name='story_paragraph_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originalstory',
            name='story_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
