# Generated by Django 2.1.4 on 2018-12-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_authorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorimage',
            name='author',
        ),
        migrations.DeleteModel(
            name='AuthorImage',
        ),
    ]
