# Generated by Django 2.1.4 on 2019-01-24 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0002_auto_20190119_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalstory',
            name='story_watchers',
            field=models.ManyToManyField(blank=True, related_name='story_watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
