# Generated by Django 2.1.4 on 2019-01-04 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190104_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalstory',
            name='story_paragraph_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
