# Generated by Django 2.1.1 on 2018-12-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20181227_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalstory',
            old_name='original_story_author_image',
            new_name='original_story_author',
        ),
    ]
