# Generated by Django 2.1.4 on 2019-01-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_originalstory_story_watchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalstory',
            name='story_watchers',
        ),
    ]
