# Generated by Django 2.1.4 on 2019-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_originalstory_story_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalstory',
            name='story_tags',
            field=models.ManyToManyField(to='tagging.StoryTags', verbose_name='Story Tags'),
        ),
    ]
