# Generated by Django 2.1.1 on 2019-01-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190106_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originalstory',
            options={'verbose_name_plural': 'Original stories'},
        ),
        migrations.AlterModelOptions(
            name='userstoryparagraphs',
            options={'verbose_name_plural': 'User paragraphs'},
        ),
        migrations.AlterField(
            model_name='originalstory',
            name='story_tags',
            field=models.ManyToManyField(to='tagging.StoryTags'),
        ),
    ]
