# Generated by Django 2.1.1 on 2019-01-06 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20190106_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalstory',
            name='story_tags',
            field=models.ManyToManyField(blank=True, null=True, to='tagging.StoryTags'),
        ),
        migrations.AlterField(
            model_name='userstoryparagraphs',
            name='paragraph_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
